sudo: required

before_install:
        - ./prepare-environment.sh
        - PUSH_NEW_IMAGE=$(./check-images.sh)
        - echo "status: $?"
        - echo $PUSH_NEW_IMAGE

script:
        - echo $TRAVIS_BRANCH
        - echo $TRAVIS_BUILD_DIR
        - echo $TRAVIS_BUILD_ID
        - echo $TRAVIS_BUILD_NUMBER
        - echo $TRAVIS_COMMIT
        - echo $TRAVIS_COMMIT_RANGE
        - echo $TRAVIS_EVENT_TYPE
        - echo $TRAVIS_PULL_REQUEST
        - echo $TRAVIS_REPO_SLUG
        - echo $TRAVIS_TEST_RESULT
        - echo $PUSH_NEW_IMAGE

env:
        - OS=ubuntu OS_VER=16.04
        - OS=fedora OS_VER=23

after_success:
        - echo $PUSH_NEW_IMAGE
        - ([[ $PUSH_NEW_IMAGE -eq 1 ]] && ./push-image.sh $OS:$OS_VER)
